"""init

Revision ID: b403afdb69a0
Revises:
Create Date: 2023-06-19 13:22:36.392704

"""
import bcrypt
from alembic import op
import sqlalchemy as sa

from watchlist.config import settings

# revision identifiers, used by Alembic.
revision = "b403afdb69a0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    movie = op.create_table(
        "movie",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("year", sa.String(length=4), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    user = op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(
        movie,
        [
            {"title": "My Neighbor Totoro", "year": "1988"},
            {"title": "Dead Poets Society", "year": "1989"},
            {"title": "A Perfect World", "year": "1993"},
            {"title": "Leon", "year": "1994"},
            {"title": "Mahjong", "year": "1996"},
            {"title": "Swallowtail Butterfly", "year": "1996"},
            {"title": "King of Comedy", "year": "1999"},
            {"title": "Devils on the Doorstep", "year": "1999"},
            {"title": "WALL-E", "year": "2008"},
            {"title": "The Pork of Music", "year": "2012"},
        ],
    )
    pwd = bcrypt.hashpw(settings.password.encode(), bcrypt.gensalt(13))
    op.bulk_insert(
        user,
        [
            {
                "name": settings.username,
                "email": settings.email,
                "hashed_password": pwd.decode(),
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("movie")
    # ### end Alembic commands ###
